### ISSUE TITLE
Help: the size of tag do not changed with matrix

### ISSUE THREAD

**Issue by mzwlevi** [Angboo/logwidgets#2]
I have changed the size of tag to 16px
```css
a.tag {
    color: grey;
    font-size: 16px;
}
```
<img width="383" alt="Screen Shot 2022-09-23 at 15 29 50" src="https://user-images.githubusercontent.com/78029539/191911307-8ca92598-529e-4ba7-8466-3efcc023c670.png">
